- name: install commandline utilities
  pacman:
    name:
      - vi
      - fzf
      - powerline
      - unrar
      - unzip
      - p7zip
      - lha
      - xz
      - bash-completion
      - zsh-completions
      - bat
      - htop
      - exa
      - ripgrep
      - neofetch
      - unarchiver
      - xsel
      - aria2
      - pkgfile
      - neovim
      - usbutils
- name: install commandline utilities (from aur)
  become: yes
  become_user: aur
  aur:
    name:
      - zplug
      - procs-bin
      - fisher