- name: add entries
  template:
    dest: /boot/loader/entries/{{ item.filename }}.conf
    src: entry.conf.j2
  loop : "{{ boot.entries }}"
  tags: boot

- name: configure loader.conf
  template:
    dest: /boot/loader/loader.conf
    src: loader.conf.j2
  tags: boot