- name: install
  become: yes
  become_user: aur
  aur:
    name: 
      - i3-gaps
      - i3status
      - dmenu
      - picom
      - dex
      - deadd-notification-center-bin
      - polybar
      - rofi
  tags:
    - gui
    - windowmanager
    - i3