- name: install
  become: yes
  become_user: aur
  aur:
    name:
      - i3-gaps
      - i3status
      - dmenu
      - picom
      - dex
      - dunst
      - polybar
      - rofi
  tags:
    - gui
    - windowmanager
    - i3
