---
apps:
  browser: false           # Web browsers
  file_manager: false      # Graphical file manager
  editor: false            # Graphical text editor
  pdf: false               # PDF viewer
  remote: false            # Remote desktop and file transfer tools
  torrent: false           # BitTorrent client
  password_manager: false  # Password manager
  file_share: false        # LAN file sharing
