- block:
  - name: install
    pacman: 
      name:
        - feh
        - thunar
        - thunar-volman
        - gvfs-smb
        - fcitx
        - fcitx-configtool
        - fcitx-gtk2
        - fcitx-gtk3
        - fcitx-mozc
        - fcitx-qt5
        - xarchiver
        - catfish
        - leafpad
        - xdg-user-dirs
        - network-manager-applet
        - autorandr

  - name: install (from aur)
    become: yes
    become_user: aur
    aur:
      name:
        - volantes-cursors

  - name: configure thunar
    lineinfile:
      path: /usr/share/gvfs/mounts/network.mount
      regexp: '^AutoMount='
      line: 'AutoMount=false'
      insertafter: EOF 

  - name: configure fcitx
    copy:
      src: 60-export-fcitx-config.sh
      dest: /etc/X11/xinit/xinitrc.d/60-export-fcitx-config.sh
      mode: "0755"
  tags:
    - gui
    - utilities