---
- hosts: all
  become: true
  remote_user: "{{ maintain_user }}"
  roles:
    - { role: base, tags: [base] }
    - { role: cui, tags: [cui] }
    - { role: devices, tags: [devices] }
    - { role: cuda, tags: [cuda] }
    - { role: media/player_viewer, tags: [media] }
    - { role: browser, tags: [browser] }
    - { role: home, tags: [home] }
