---
- hosts: sandbox
  become: true
  vars_files:
    - ../vars/secret.yml
  roles:
    - base
  tasks:
    - name: Verify yay installation
      ansible.builtin.command: which yay
      register: yay_result
      changed_when: false
      
    - name: Show yay location
      ansible.builtin.debug:
        msg: "yay installed at: {{ yay_result.stdout }}"
        
    - name: Verify essential packages
      ansible.builtin.package_facts:
        manager: auto
        
    - name: Check if git is installed
      ansible.builtin.debug:
        msg: "git version: {{ ansible_facts.packages.git[0].version }}"
      when: "'git' in ansible_facts.packages"