---
- hosts: "{{ target | default('all') }}"
  become: true
  roles:
    - { role: base, tags: [base] }
    - { role: shell, tags: [shell] }
    - { role: devices, tags: [devices] }
    - { role: desktop, tags: [desktop] }
    - { role: apps, tags: [apps] }
    - { role: media, tags: [media] }
    - { role: office, tags: [office] }
    - { role: development, tags: [development] }
    - { role: virtualization, tags: [virtualization] }
