---
- hosts:
    - localpc
  remote_user: "ansible"
  become: true
  gather_facts: true
  vars_files:
    - ../vars/secret.yml
  roles:
    - role: debug
    - role: system/user
    - role: system/package
    - role: system/makepkg
    - role: system/locale
    - role: system/host
    - role: system/man
    - role: system/driver/graphic
    #- role: system/defaultapplication
    - role: system/suspend
    - role: system/cronie

    - role: network/timesync
    - role: network/networkmanager
    - role: network/xrdp

    - role: runtime/python
    - role: runtime/python310
    - role: runtime/java
    - role: runtime/nodejs

    - role: cui/utils
    - role: cui/kawazu
    #- role: cui/alacritty
    - role: cui/tmux
    - role: cui/wezterm

    - role: shell/bash
    - role: shell/fish

    - role: gui/xorg
    - role: gui/lightdm
    - role: gui/lightdm_mini_greeter
    - role: gui/i3
    - role: gui/thunar
    - role: gui/nemo
    - role: gui/volantes-cursors
    - role: gui/utils
    - role: gui/fcitx

    - role: browser/firefox
    - role: browser/chromium
    - role: browser/profilesyncdaemon

    - role: development/docker
    - role: development/cuda
    - role: development/git

    - role: font/noto
    - role: font/plemoljp
    - role: font/utilities

    - role: multimedia/gthumb
    - role: multimedia/mcomix
    - role: multimedia/imagemagick

    - role: security/authy
    - role: security/firejail
    - role: security/gnome_keyring
    - role: security/keepassxc

    - role: storage/veracrypt
    - role: storage/nfs

    - role: homedir
