---
- hosts: all
  become: true
  remote_user: "{{ maintain_user }}"
  roles:
    - { role: base, tags: [base] }
    - { role: bluetooth, tags: [bluetooth] }
    - { role: cui, tags: [cui] }
    - { role: gui/i3, tags: [gui] }
    - { role: sound/pipewire, tags: [sound] }
    - { role: browser, tags: [browser] }
    - { role: media/player_viewer, tags: [media] }
    - { role: development, tags: [development] }
    - { role: storage, tags: [storage] }
    - { role: home, tags: [home] }
