---
- hosts: sandbox
  become: true
  vars_files:
    - ../vars/secret.yml
  roles:
    - { role: init, tags: [init, never] }
    - { role: base, tags: [base] }
    - { role: cui, tags: [cui] }
    - { role: devices, tags: [devices] }
    - { role: gui, tags: [gui] }
