---
- name: install sway
  become: true
  become_user: aur
  aur:
    name:
      - sway
      - swaylock
      - swayidle
      - swaybg
      - wmenu
      - waybar
      - i3status
      - wttrbar
      - waybar-module-pacman-updates-git
      - sov
      - swayidle
      - bumblebee-status
      - python-i3ipc
      - python-pytz
      - python-tzlocal

- name: set default session
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    regexp: "^user-session="
    line: "user-session=sway"
    insertafter: '\[Seat:\*\]'

- name: configure sway.desktop
  block:
    - lineinfile:
        path: /usr/share/wayland-sessions/sway.desktop
        regexp: "DesktopNames="
        line: "DesktopNames=sway"
        insertafter: '\[Desktop Entry\]'

    - lineinfile:
        path: /usr/share/wayland-sessions/sway.desktop
        regexp: "^Exec="
        line: "Exec=env SDL_VIDEODRIVER=wayland _JAVA_AWT_WM_NONREPARENTING=1 QT_QPA_PLATFORM=wayland XDG_CURRENT_DESKTOP=sway XDG_SESSION_DESKTOP=sway /usr/bin/sway"
