---
- block:
  - name: install
    pacman: 
      name:
        - qemu
        - virt-manager
        - libvirt
        - qemu-arch-extra
  - name: load virtio
    modprobe:
      name: virtio
  tags: 
    - development
    - qemu
