---
- block:
    - name: install
      pacman:
        name:
          - qemu
          - virt-manager
          - libvirt
          - edk2-ovmf
          - dnsmasq

    - name: configure libvirt
      copy:
        src: libvirt-qemu.conf
        dest: /etc/libvirt/qemu.conf
        mode: "0755"

    - name: configure libvirtd
      lineinfile:
        path: /etc/libvirt/libvirtd.conf
        regexp: "^#? *unix_sock_group"
        line: 'unix_sock_group = "libvirt"'

    - name: configure libvirtd
      lineinfile:
        path: /etc/libvirt/libvirtd.conf
        regexp: "^#? *unix_sock_rw_perms"
        line: 'unix_sock_rw_perms = "0770"'

    - name: add {{ secret.user.name }} to group libvirt,kvm
      user:
        name: "{{ secret.user.name }}"
        groups:
          - libvirt
          - kvm
        append: yes

    - name: enable libvirtd
      service:
        name: libvirtd
        enabled: yes
  tags:
    - development
    - qemu
