- block:
  - name: install
    pacman:
      name:
        - zsh
        - zsh-completions

  - name: install (from aur)
    become: yes
    become_user: aur
    aur:
      name:
        - zplug
  tags:
    - cui
    - zsh