- block:
    - name: install video driver
      pacman:
        name:
          - xf86-video-amdgpu
          - mesa
          - mesa-vdpau
          - libva-mesa-driver
    - name: enable early kms start
      lineinfile:
        path: /etc/mkinitcpio.conf
        regexp: " *MODULES="
        line: "MODULES=(amdgpu)"
        insertafter: "# *MODULES="
      register: mkinitcpio_output
    - name: run mkinitcpio
      command: mkinitcpio -P
      when: mkinitcpio_output.changed
  tags:
    - system
    - driver
