---
- name: install network diagnostic tools
  become: true
  become_user: aur
  aur:
    name:
      # Network diagnostics
      - tcpdump # packet analyzer
      - iperf # network performance
      - net-tools # legacy network tools
      - nmap # network scanner
      - traceroute # route tracing
      - dig # DNS lookup
      - whois # domain information

      # SSH utilities (use with caution)
      - sshpass # SSH password automation

- name: configure ethernet static IP
  include_tasks: ethernet_config.yml
  when:
    - ethernet is defined
    - ethernet.interface is defined
    - ethernet.static_ip is defined

- name: display post-ansible instructions
  debug:
    msg: |
      NOTICE: Ethernet static IP configuration completed.

      The static IP configuration has been saved to NetworkManager.
      Changes will take effect automatically after system reboot.

      Current session maintains DHCP connectivity for safety.

      To apply immediately (optional):
      sudo systemctl restart NetworkManager

      To verify configuration:
      nmcli connection show "{{ hostvars[inventory_hostname]['current_connection']['stdout'] | default('Wired connection 1') }}"
  when:
    - ethernet is defined
    - ethernet.interface is defined
    - ethernet.static_ip is defined
