---
- hosts: kamo3work
  remote_user: "ansible"
  become: true
  gather_facts: no
  vars_files:
    - vars/secret.yml
  roles:
    - { role: debug,tags: ["never", "debug"] }
    - { role: base, tags: ["base"]}
    - { role: gui/displayserver, tags: ["gui","displayserver"]}
    - { role: gui/displaymanager, tags: ["gui","displaymanager"]}
    - { role: gui/windowmanager, tags: ["gui","windowmanager"]}
    - { role: utilities/cui, tags: ["utilites","utilities_cui","cui"]}