---
- hosts:
    - work
  remote_user: "ansible"
  become: true
  gather_facts: true
  vars_files:
    - vars/secret.yml
  roles:
    - role: debug
    - role: system/user
    - role: system/package
    - role: system/makepkg
    - role: system/locale
    - role: system/host
    - role: system/man
    - role: system/benchmark
    - role: system/bluetooth
    - role: system/driver/virtualbox
    - role: system/defaultapplication
    - role: system/suspend
    - role: system/cronie

    - role: network/timesync
    - role: network/networkmanager

    - role: runtime/python
    - role: runtime/java
    - role: runtime/nodejs

    - role: cui/utils
    - role: cui/kawazu
    - role: cui/alacritty
    - role: cui/tmux

    - role: shell/bash
    - role: shell/fish

    - role: gui/xorg
    - role: gui/i3
    - role: gui/lightdm
    - role: gui/lightdm_mini_greeter
    - role: gui/thunar
    - role: gui/nemo
    - role: gui/volantes-cursors
    - role: gui/utils
    - role: gui/fcitx

    - role: browser/firefox
    - role: browser/chromium
    - role: browser/profilesyncdaemon

    - role: cad/cura
    - role: cad/librecad
    - role: cad/freecad
    - role: cad/kicad

    - role: development/avr
    - role: development/docker
    - role: development/git
    - role: development/m5stack
    - role: development/virtualbox
    - role: development/vscode
    #    - role: development/qemu

    - role: document/libreoffice
    - role: document/okular

    - role: font/cica
    - role: font/mplus
    - role: font/nerd-fonts
    - role: font/noto
    - role: font/setfont
    - role: font/ibm_plex
    - role: font/plemoljp
    - role: font/utilities

    - role: multimedia/pulseaudio
    - role: multimedia/ffmpeg
    - role: multimedia/gimp
    - role: multimedia/gthumb
    - role: multimedia/imagemagick
    - role: multimedia/inkscape
    - role: multimedia/mcomix
    - role: multimedia/vlc
    #    - role: multimedia/spotify
    - role: multimedia/utils

    - role: network_client/filezilla
    - role: network_client/remmina
    - role: network_client/qbittorrent

    - role: security/authy
    - role: security/firejail
    - role: security/gnome_keyring
    - role: security/keepassxc

    - role: storage/filesystem
    - role: storage/gparted
    - role: storage/samba
    - role: storage/veracrypt
    - role: storage/rclone

    - role: communication/slack
    #    - role: communication/discord
    - role: communication/zoom

    - role: printer

    - role: homedir

- hosts:
    - kamo3work
  remote_user: "ansible"
  become: true
  gather_facts: false
  vars_files:
    - vars/secret.yml
  roles:
    - role: system/driver/amdgpu
