- hosts:
    - kamo3work
    - kamo3work_dev
  remote_user: "ansible"
  become: true
  gather_facts: no
  vars_files:
    - vars/secret.yml
  roles:
    - role: system/user
    - role: system/package
    - role: system/locale
    - role: system/host
    - role: system/boot

    - role: system/driver/virtualbox
    - role: gui/xorg
    - role: gui/i3_gaps
    - role: gui/lightdm
    - role: gui/lightdm_webkit2_greeter
    - role: gui/lightdm_webkit_theme_litarvan
    - role: gui/thunar
    - role: gui/volantes-cursors
    - role: gui/utils

    - role: cui/utils
    - role: cui/kawazu

    - role: shell/bash
    - role: shell/fish
    - role: shell/zsh

    - role: browser/firefox
    - role: browser/chromium
    - role: browser/profilesyncdaemon

    - role: cad/cura
    - role: cad/librecad
    - role: cad/freecad
    - role: cad/kicad
    - role: development/avr
    - role: development/docker
    - role: development/git
    - role: development/m5stack
    - role: development/virtualbox
    - role: development/vscode

    - role: runtime/python
    - role: runtime/java
    - role: runtime/nodejs

    - role: font/cica
    - role: font/mplus
    - role: font/nerd-fonts
    - role: font/noto
    - role: font/setfont
    - role: font/utilities

    - role: multimedia/ffmpeg
    - role: multimedia/gimp
    - role: multimedia/gthumb
    - role: multimedia/imagemagick
    - role: multimedia/inkscape
    - role: multimedia/mcomix
    - role: multimedia/vlc

    - role: network_client/filezilla
    - role: network_client/remmina
    - role: network_client/qbittorrent

    - role: security/authy
    - role: security/firejail
    - role: security/gnome_keyring
    - role: security/keepassxc

    - role: storage/dropbox
    - role: storage/filesystem
    - role: storage/gparted
    - role: storage/grive
    - role: storage/samba
    - role: storage/veracrypt

    - role: cui/alacritty
    - role: cui/tmux