---
- hosts: kamo3work
  remote_user: "ansible"
  become: true
  gather_facts: no
  vars_files:
    - vars/secret.yml
  roles:
    - { role: debug,tags: ["never", "debug"] }
    - { role: base, tags: ["base"]}
    - { role: gui/displayserver, tags: ["gui","displayserver"]}
    - { role: gui/displaymanager, tags: ["gui","displaymanager"]}
    - { role: gui/windowmanager, tags: ["gui","windowmanager"]}
    - { role: fonts, tags: ["fonts"]}
    - { role: gui/desktop, tags: ["gui","desktop"]}
    - { role: utilities/cui, tags: ["utilities","utilities_cui","cui"]}
    - { role: utilities/gui, tags: ["utilities","utilities_gui","gui"]}
    - { role: browser/firefox, tags: ["browser","firefox"]}
    - { role: browser/chromium, tags: ["browser","chromium"]}
    - { role: browser/googlechrome, tags: ["browser","googlechrome"]}
    - { role: browser/profileSyncDaemon, tags: ["browser","profileSyncDaemon"]}

    - { role: development/vscode, tags: ["development","vscode"]}
    - { role: development/git, tags: ["development","git"]}
    - { role: development/github-cli, tags: ["development","github-cli"]}
    - { role: development/virtualbox, tags: ["development","virtualbox"]}
    - { role: development/docker, tags: ["development","docker"]}