---
- hosts: kamo3_work
  gather_facts: no
  vars_files:
    - vars/common.yml
    - vars/kamo3_work_dev/common.yml
    - vars/kamo3_work_dev/secret.yml
  roles:
    - { role: debug,tags: ["never", "debug"] }
    - { role: init,tags: ["never", "init"] }