---
- name: Install greetd + tuigreet
  aur:
    name:
      - greetd
      - greetd-tuigreet
    state: present
    use: paru
  become: false
  when: desktop.display_manager == 'greetd'

- name: Configure greetd (launch Hyprland via uwsm)
  ansible.builtin.template:
    src: greetd-config.toml.j2
    dest: /etc/greetd/config.toml
    mode: "0644"
    owner: root
    group: root
  become: true
  when: desktop.display_manager == 'greetd'
  notify: restart greetd


- name: Enable greetd.service
  ansible.builtin.systemd:
    name: greetd
    enabled: true
  become: true
  when: desktop.display_manager == 'greetd'
