---
# fcitx5 input method installation and configuration

- name: Install fcitx5 input method
  aur:
    name:
      # Core fcitx5 packages
      - fcitx5 # Main fcitx5 package
      - fcitx5-configtool # Configuration GUI
      - fcitx5-gtk # GTK integration
      - fcitx5-qt # Qt integration

      # Japanese input method
      - fcitx5-mozc # Japanese input (Mozc)

      # Theme and appearance
      - fcitx5-material-color # Material color theme

    state: present
  become_user: "{{ ansible_user }}"

- name: Create fcitx5 environment configuration
  ansible.builtin.copy:
    content: |
      # fcitx5 environment variables
      export GTK_IM_MODULE=fcitx
      export QT_IM_MODULE=fcitx
      export XMODIFIERS=@im=fcitx
      export INPUT_METHOD=fcitx5
      export GLFW_IM_MODULE=ibus  # For some applications
    dest: /etc/profile.d/60-fcitx5.sh
    mode: "0644"
  become: true

