---
# Font management - minimal or full installation based on old GUI role

- name: Install minimal font set (always installed)
  aur:
    name:
      # Basic system fonts
      - noto-fonts # Basic Latin fonts
      - noto-fonts-cjk # Japanese/Chinese/Korean support
      - noto-fonts-emoji # Basic emoji support
      - ttf-dejavu # Monospace font (system default)
      - fontconfig # Font configuration system
      - ttf-cica # Programming font with Japanese support
    state: present
  become_user: "{{ ansible_user }}"

- name: Install additional fonts for full installation
  aur:
    name:
      # Additional programming/Monospace fonts
      - ttf-plemoljp-bin # PlemolJP font family
      - ttf-ibm-plex # IBM Plex font family

      # Design/Display fonts
      - ttf-bizter # Bizter font
      - ttf-line-seed # Line Seed font

      # Font management tools
      - gucharmap # Character map utility
      - font-manager # Font management GUI

    state: present
  become_user: "{{ ansible_user }}"
  when: gui.fonts.install == "full"

- name: Create system-wide fontconfig
  ansible.builtin.template:
    src: fontconfig.conf.j2
    dest: "/etc/fonts/local.conf"
    mode: "0644"
  become: true
  vars:
    gui_fonts: "{{ gui_fonts[gui.fonts.install] }}"
  when: not system_fontconfig_stat.stat.exists

- name: Refresh font cache
  ansible.builtin.command: fc-cache -fv
  become_user: "{{ ansible_user }}"
  changed_when: false
