---
# GNOME desktop environment installation

- name: Install GNOME minimal desktop environment (always installed)
  aur:
    name:
      # Core GNOME packages (minimal = gnome group)
      - gnome # GNOME desktop environment meta-package
      - gnome-tweaks # GNOME customization tool

      # GNOME Shell extensions (always installed with GNOME)
      - gnome-shell-extension-appindicator  # System tray support
      - gnome-browser-connector            # Browser extension connector
      - gnome-shell-extension-kimpanel     # Input method panel for fcitx5

    state: present
  become_user: "{{ ansible_user }}"
  when: desktop.environment.install | default(false)

- name: Install additional GNOME packages for full installation
  aur:
    name:
      # Additional GNOME applications and tools
      - gnome-extra # Additional GNOME applications
      - dconf-editor # Configuration editor

      # GNOME-specific utilities
      - extension-manager # GNOME Shell extension manager

      # GNOME applications (beyond gnome meta-package)
      - gnome-text-editor # New GNOME text editor
      - gnome-console # New GNOME terminal

    state: present
  become_user: "{{ ansible_user }}"
  when:
    - desktop.environment.install | default(false)
    - desktop.environment.gnome_install | default("minimal") == "full"
