---
development:
  editor: false            # visual-studio-code-bin
  git_tools: false         # git-lfs + lazygit + git-delta + difftastic + tokei + gibo + cocogitto
  cli_tools: false         # jq + yq + ghq + github-cli
