---
development:
  editor: false            # Graphical code editor
  git_tools: false         # Git development tools
  cli_tools: false         # Development CLI tools
  docker: false            # Docker development tools
