- name: install qemu packages
  become: true
  become_user: aur
  aur:
    name:
      - qemu-full
      - libvirt
      - virt-manager
      - dnsmasq

- name: add {{ maintain_user }} to group libvirt
  user:
    name: "{{ maintain_user }}"
    groups: libvirt
    append: yes

- name: enable libvirt
  service:
    name: libvirtd
    enabled: yes
