- block:
  - name: install lightdm
    pacman:
      name: lightdm

  - name: enable lightdm
    service:
      name: lightdm.service
      enabled: yes

  - name: install lightdm-webkit-theme-litarvan
    pacman:
      name: lightdm-webkit-theme-litarvan

  - name: configure lightdm.conf
    lineinfile: 
      path: /etc/lightdm/lightdm.conf
      regexp: '^\s*greeter-session=.*'
      line: 'greeter-session=lightdm-webkit2-greeter'
      insertafter: '\[Seat:\*\]'
    notify: restart lightdm

  - name: configure lightdm-webkit.conf
    lineinfile: 
      path: /etc/lightdm/lightdm-webkit2-greeter.conf
      regexp: '^\s*webkit_theme\s*=\s*.*'
      line: 'webkit_theme=litarvan'
      insertafter: '\[greeter]'
    notify: restart lightdm
  tags:
    - gui
    - lightdm
    - displaymanager