- block:
    - name: install
      pacman:
        name: lightdm-gtk-greeter

    - name: configure lightdm.conf
      lineinfile:
        path: /etc/lightdm/lightdm.conf
        regexp: '^\s*greeter-session=.*'
        line: "greeter-session=lightdm-gtk-greeter"
        insertafter: '\[Seat:\*\]'
  tags:
    - gui
    - lightdm
