---
- name: Check if bluetooth.enable is defined and true
  block:
    - name: install bluetooth packages
      pacman:
        name:
          - bluez
          - bluez-utils
          - blueman
          - pulseaudio-alsa
          - pulseaudio-bluetooth
    - name: enable bluetooth
      service:
        name: bluetooth
        enabled: yes
  when: bluetooth.enable | default(true) | bool
