---
# Common GUI utilities for all desktop environments

- name: Install common GUI utilities
  aur:
    name:
      # Terminal emulators
      - alacritty             # GPU-accelerated terminal
      - kitty                 # Modern GPU-accelerated terminal
      
      # File management
      - nemo                  # File manager (Cinnamon-based)
      - file-roller          # Archive manager
      
      # Text editor (for environments without built-in editor)
      - featherpad            # Qt-based text editor
      
      # Web browsers
      - firefox               # Firefox browser
      - chromium              # Chromium browser
      - network-manager-applet # NetworkManager GUI
      
      # Media viewers and players
      - mpv                   # Video player
      - vlc                   # VLC media player
      - vlc-plugins-all       # VLC all plugins/codecs
      - imv                   # Image viewer for Wayland
      
      # PDF viewer
      - zathura               # Minimal PDF viewer
      - zathura-pdf-poppler   # PDF backend for zathura
      
      # System utilities
      - xdg-user-dirs        # User directory management
      
      # Wayland utilities (common for all environments)
      - grim                  # Screenshot utility for Wayland
      - slurp                 # Screen area selection for Wayland
      - wl-clipboard          # Wayland clipboard utilities
      - wev                   # Wayland event viewer (debugging)
      
      # Fonts and rendering
      - fontconfig            # Font configuration
      
      # Desktop portals (required for modern apps)
      - xdg-desktop-portal    # Base desktop portal framework
      - xdg-desktop-portal-wlr # wlroots-based portal implementation
      
      # Theme and appearance
      - qt5-wayland           # Qt5 Wayland support
      - qt6-wayland           # Qt6 Wayland support
      - adwaita-qt5           # Adwaita theme for Qt5
      - adwaita-qt6           # Adwaita theme for Qt6
      
    state: present
  become_user: "{{ ansible_user }}"

- name: Install keyring and secret management
  pacman:
    name:
      - gnome-keyring         # GNOME keyring daemon
      - seahorse              # Keyring management GUI
      - libsecret             # Secret service library
    state: present