---
# Hyprland desktop environment installation

- name: Install Hyprland desktop environment
  aur:
    name:
      # Core Hyprland packages
      - hyprland                # Hyprland compositor
      - hyprpaper              # Wallpaper utility for Hyprland
      - hypridle               # Idle management for Hyprland
      - hyprlock               # Screen locker for Hyprland
      - hyprpicker             # Color picker for Hyprland
      
      # Hyprland-specific utilities
      - waybar                 # Status bar for Wayland
      - wofi                   # Application launcher for Wayland
      - rofi-lbonn-wayland-git # Alternative application launcher
      - wlogout                # Logout menu
      - swaynotificationcenter # Notification daemon (swaync)
      - kanshi                 # Dynamic display configuration
      - wlr-randr             # Display management for wlroots
      - wlroots               # Wayland compositor library
      - wob                   # Wayland overlay bar (volume/brightness)
      
      # Clipboard and screenshot management
      - clipman               # Clipboard manager
      - cliphist              # Clipboard history
      - swappy                # Screenshot annotation tool
      
      # Additional utilities
      - foot                  # Alternative terminal emulator
      - wallutils             # Wallpaper utilities
      - dex                   # Desktop entry execution (autostart)
      
      # Desktop portals and integration
      - xdg-desktop-portal-hyprland  # Desktop portal for Hyprland
      - polkit-gnome           # Policy kit authentication agent
      
      # X11 compatibility for legacy applications
      - xorg-xwayland          # X11 compatibility layer
      
    state: present
  become_user: "{{ ansible_user }}"
  when: gui.desktop.install | default(false)