---
# GUI role main tasks - Desktop environment installation and configuration

- name: Install common GUI utilities
  ansible.builtin.import_tasks: common.yml
  when: gui.common.install | default(true)
  tags: [gui, common]

- name: Install fonts
  ansible.builtin.import_tasks: fonts.yml
  tags: [gui, fonts]

- name: Install fcitx5 input method
  ansible.builtin.import_tasks: fcitx5.yml
  when: gui.inputmethod.install | default(true)
  tags: [gui, fcitx5, inputmethod]

- name: Install GNOME desktop environment
  ansible.builtin.import_tasks: gnome.yml
  when: gui.desktop.environment == "gnome"
  tags: [gui, gnome]

- name: Install Hyprland desktop environment  
  ansible.builtin.import_tasks: hyprland.yml
  when: gui.desktop.environment == "hyprland"
  tags: [gui, hyprland]

- name: Configure display manager
  ansible.builtin.import_tasks: display_manager.yml
  when: gui.display_manager.install | default(false)
  tags: [gui, display-manager]