---
- name: install xorg packages
  pacman:
    name:
      - xorg-server
      - xorg-apps
      - xorg-xinit
      - xorg-twm
      - xorg-xclock
      - xterm

- name: install driver (intel)
  pacman:
    name:
      - mesa
      - xf86-video-intel
  when: gui.driver == "intel"

- name: install icon theme
  become: true
  become_user: aur
  aur:
    name:
      - volantes-cursors
- name: lightdm
  block:
    - name: install lightdm
      pacman:
        name: lightdm

    - name: enable lightdm
      service:
        name: lightdm.service
        enabled: yes

    - name: install lightdm-mini-greeter
      become: true
      become_user: aur
      aur:
        name: lightdm-mini-greeter

    - name: configure lightdm.conf
      lineinfile:
        path: /etc/lightdm/lightdm.conf
        regexp: '^\s*greeter-session=.*'
        line: "greeter-session=lightdm-mini-greeter"
        insertafter: '\[Seat:\*\]'

    - name: configure lightdm-mini-greeter.conf
      lineinfile:
        path: /etc/lightdm/lightdm-mini-greeter.conf
        regexp: '^\s*user\s*=.*'
        line: "user = {{ maintain_user }}"
        insertafter: '\[greeter\]'
  notify: restart lightdm

- name: i3
  block:
    - name: install i3
      become: true
      become_user: aur
      aur:
        name:
          - i3-wm
          - i3status
    - name: set default session
      lineinfile:
        path: /etc/lightdm/lightdm.conf
        regexp: "^user-session="
        line: "user-session=i3"
        insertafter: '\[Seat:\*\]'

- name: install gui utils
  become: true
  become_user: aur
  aur:
    name:
      - picom
      - dex
      - dunst
      - polybar
      - rofi
      - nemo
      - feh
      - catfish
      - leafpad
      - xdg-user-dirs
      - network-manager-applet
      - autorandr
      - file-roller
      - flameshot
      - dwall-git
      - ulauncher
