---
- name: install xorg packages
  pacman:
    name:
      - xorg
      - xorg-server
      - xorg-apps
      - xorg-xinit
      - xterm

- name: install driver (intel)
  pacman:
    name:
      - mesa
      - mesa-utils
  when: gui.driver == "intel"

- name: install icon theme
  become: true
  become_user: aur
  aur:
    name:
      - volantes-cursors
- name: lightdm
  block:
    - name: install lightdm
      pacman:
        name: lightdm

    - name: enable lightdm
      service:
        name: lightdm.service
        enabled: yes

    - name: install lightdm-mini-greeter
      become: true
      become_user: aur
      aur:
        name: lightdm-mini-greeter

    - name: configure lightdm.conf
      lineinfile:
        path: /etc/lightdm/lightdm.conf
        regexp: '^\s*greeter-session=.*'
        line: "greeter-session=lightdm-mini-greeter"
        insertafter: '\[Seat:\*\]'

    - name: configure lightdm-mini-greeter.conf
      lineinfile:
        path: /etc/lightdm/lightdm-mini-greeter.conf
        regexp: '^\s*user\s*=.*'
        line: "user = {{ maintain_user }}"
        insertafter: '\[greeter\]'
  notify: restart lightdm

- name: i3
  block:
    - name: install i3
      become: true
      become_user: aur
      aur:
        name:
          - i3-wm
          - i3status
    - name: set default session
      lineinfile:
        path: /etc/lightdm/lightdm.conf
        regexp: "^user-session="
        line: "user-session=i3"
        insertafter: '\[Seat:\*\]'

- name: install gui utils
  become: true
  become_user: aur
  aur:
    name:
      - bumblebee-status
      - python-i3ipc
      - python-pytz
      - python-tzlocal
      - alacritty
      - picom
      - dex
      - dunst
      - polybar
      - rofi
      - nemo
      - feh
      - catfish
      - leafpad
      - xdg-user-dirs
      - network-manager-applet
      - autorandr
      - file-roller
      - flameshot
      - dwall-git
      - ulauncher
      - filezilla
      - remmina
      - qbittorrent
      - keepassxc
      - gparted

- name: install fcitx
  become: true
  become_user: aur
  aur:
    name:
      - fcitx5-im
      - fcitx5-mozc

- name: configure fcitx
  copy:
    src: 60-export-fcitx-config.sh
    dest: /etc/X11/xinit/xinitrc.d/60-export-fcitx-config.sh
    mode: "0755"

- name: install seahose
  pacman:
    name:
      - gnome-keyring
      - seahorse
      - libsecret

- name: insert pam.d for seahorse
  lineinfile:
    path: /etc/pam.d/login
    line: "auth optional pam_gnome_keyring.so"
    regexp: "^auth\\s+optional\\s+pam_gnome_keyring.so"
    insertafter: "^auth"
- name: insert pam.d for seahorse
  lineinfile:
    path: /etc/pam.d/login
    line: "session optional pam_gnome_keyring.so auto_start"
    regexp: "^session\\s+optional\\s+pam_gnome_keyring.so\\s+auto_start"
    insertafter: "^session"
