---
- name: install xorg packages
  pacman:
    name:
      - xorg
      - xorg-server
      - xorg-apps
      - xorg-xinit
      - xterm

- name: install utils
  become: true
  become_user: aur
  aur:
    name:
      - picom
      - dunst
      - feh
      - autorandr
