- hosts:
    - usb
    - usb_dev
  remote_user: "ansible"
  become: true
  gather_facts: yes
  vars_files:
    - vars/secret.yml
  roles:
    - { role: debug, tags: ["never", "debug"] }
    - role: base/common
    - role: base/graphic_driver
    - role: base/sound

    - role: cui/common
    - role: cui/bash

    - role: gui/displayserver/xorg
    - role: gui/displaymanager/lightdm
    - role: gui/desktop_environment/xfce
    - role: gui/utilities

    - role: fonts/noto
    - role: fonts/cica
    - role: fonts/setfont

    - role: multimedia/vlc
    - role: multimedia/mcomix

    - role: storage/veracrypt
    - role: storage/open-iscsi

    - role: system/overlayfs
    - role: system/disable_ipv6

    - role: custom/usb
