- block:
    - name: install
      pacman:
        name:
          - gnome-keyring
          - seahorse
          - libgnome-keyring
    - name: configure xprofile
      copy:
        src: 70-run-gnome-keyring.sh
        dest: /etc/X11/xinit/xinitrc.d/70-run-gnome-keyring.sh
        mode: "0755"
  tags:
    - security
    - gnome-keyring
