---
# Default variables for base role - using role-scoped naming

base:
  # Pacman configuration
  parallel_downloads: 5

  # Essential packages
  essential_packages:
    # Core system
    - base-devel
    - linux-headers
    - archlinux-keyring
    
    # Network
    - networkmanager
    - openssh
    - wget
    - curl
    - inetutils
    
    # Essential tools
    - git
    - vim
    - nano
    - man-db
    - tree
    - htop
    - less
    - which
    - sudo
    - rsync
    
    # Archive handling
    - unzip
    - zip
    - p7zip
    - unrar
    - atool
    # tar, gzip are in base group
    
    # System tools  
    - lsof
    - strace
    - smartmontools
    - reflector
    
    # Hardware information
    - lshw
    - hwinfo  
    - pciutils
    - usbutils
    - dmidecode
    
    # File systems
    - dosfstools
    - ntfs-3g
    - btrfs-progs
    
    # Security tools
    - logwatch
    - rkhunter

  # AUR packages (optional)
  aur_packages: []
    # - yay-bin  # Alternative to building yay
    # - google-chrome

  # System configuration
  hostname: archlinux  # Default hostname (should be overridden in inventory)
  
  # Note: main_user configuration moved to init role
  # Note: static_network configuration moved to init role

  # Security configuration