---
virtualization:
  kvm: false                   # KVM virtualization
  kvm_default_network: true    # Enable libvirt default NAT (192.168.122.0/24). Set false if host NIC uses the same subnet
  virtualbox: false            # VirtualBox virtualization
