---
# Default variables for virtualization role - QEMU/KVM virtualization for home use

virtualization:
  # Core virtualization installation
  install: false # Install virtualization tools

  # QEMU configuration - using desktop variant (lighter for home use)

  # Networking configuration
  networking:
    enable_default_network: true # Enable default NAT network

