---
- hosts: all
  become: true
  remote_user: "{{ maintain_user }}"
  roles:
    - { role: base, tags: [base] }
    - { role: devices, tags: [devices] }
    - { role: cui, tags: [cui] }
    - { role: network, tags: [network] }
    - { role: gui, tags: [gui] }
    - { role: cad, tags: [cad] }
    - { role: browser, tags: [browser] }
    - { role: media/player_viewer, tags: [media] }
    - { role: media/editor, tags: [media] }
    - { role: document, tags: [document] }
    - { role: development, tags: [development] }
    - { role: containers, tags: [containers] }
    - { role: storage, tags: [storage] }
    - { role: home, tags: [home] }
