---
- name: enable essential services
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - sshd # SSH daemon (openssh package)
    - systemd-timesyncd # Time synchronization (systemd)
    - systemd-resolved # DNS resolver (systemd)
    - NetworkManager # Network management (networkmanager package)
  ignore_errors: true # Some services might not be available in all environments

- name: install and enable cronie
  block:
    - name: install cronie
      pacman:
        name: cronie
    - name: enable cronie
      service:
        name: cronie
        enabled: true
  when: enable_cron | default(true)
