---
- name: "install {{ microcode }}-ucode"
  pacman:
    name: "{{ microcode }}-ucode"
  when: microcode is defined

- name: change mkinitcpio.conf
  lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: '^HOOKS=\((.*base(?!.*microcode).*)\)$'
    line: 'HOOKS=(\1 microcode)'
    backrefs: yes
    state: present
  when: microcode is defined
  notify: regenerate initramfs

- name: regenerate initramfs immediately
  command: mkinitcpio -P
  when:
    - microcode is defined
    - regenerate_initramfs_immediately | default(true)

- name: copy hostname
  template:
    src: hostname.j2
    dest: /etc/hostname
    mode: 0644

- name: copy hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    mode: 0644

- name: enable suspend (conditional)
  lineinfile:
    path: /etc/systemd/logind.conf
    regexp: '^\s*#?HandlePowerKey='
    line: "HandlePowerKey=suspend"
    insertafter: '^\[Login\]'
  when: enable_suspend_on_power | default(false)

- name: Configure journalctl log size
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "^#?SystemMaxUse="
    line: "SystemMaxUse=50M"
    state: present
