---
devices:
  cpu:
    vendor: amd # AMD Ryzen (Cezanne)
  gpu:
    type: nvidia
    cuda: true # RTX 3060 — used for Stable Diffusion
  audio: true
  bluetooth: true
  printer: false

desktop:
  environment: xfce
  display_manager: xrdp
  ime: fcitx5

apps:
  browser: true
  file_manager: false
  editor: true
  pdf: false
  remote: false
  torrent: false
  password_manager: false
  file_share: false

media:
  cli_tools: true
  playback: true
  editing: false

development:
  editor: false
  git_tools: true
  cli_tools: true
  docker: true

storage:
  cloud_sync: false
  encryption: true
  nfs: true
  iscsi: true
  sshfs_server: true
  btrfs_mounts:
    - subvol: "@stable_diffusion_data"
      mountpoint: /sd_data
      uuid: 35a691a7-7d8c-424d-b179-95444aa59e6b
    - subvol: "@sd_output"
      mountpoint: /sd_output
      uuid: 86fa44b7-d1a9-4641-a3d3-ab4eb9990cca

network:
  wired:
    interface: enp7s0
    ip: 192.168.100.10/24
    gateway: 192.168.100.1
    dns:
      - 192.168.100.1
  wifi:
    interface: wlp6s0
    ssid: "{{ wifi_ssid }}"
    password: "{{ wifi_password }}"
