---
- block:
    - name: configure
      lineinfile:
        path: /etc/makepkg.conf
        regexp: " *MAKEFLAGS"
        line: MAKEFLAGS="-j $(nproc)"
        insertafter: "#MAKEFLAGS="
  tags:
    - system
    - makepkg
