- name: copy iscsiscript
  copy:
    src: iscsi.sh
    dest: /home/{{secret.user.name}}/iscsi.sh
    mode: "755"
    owner: "{{secret.user.name}}"
    group: "{{secret.user.name}}"
- name: install session clean script
  copy:
    src: sessionclean
    dest: /usr/local/bin/sessionclean
    mode: "755"
    owner: root
    group: wheel