---
- name: Install PipeWire stack
  aur:
    name:
      - pipewire           # core
      - pipewire-alsa      # ALSA compatibility
      - pipewire-pulse     # PulseAudio compatibility
      - pipewire-jack      # JACK compatibility
      - wireplumber        # session manager
      - alsa-utils         # alsamixer / amixer
    state: present
    use: paru
  become: false
