---
- name: Install Bluetooth packages
  aur:
    name:
      - bluez
      - bluez-utils
    state: present
    use: paru
  become: false

- name: Enable bluetooth.service
  ansible.builtin.systemd:
    name: bluetooth
    enabled: true
    state: started
  become: true
