---
# Bluetooth support configuration

- name: Install Bluetooth packages
  aur:
    name:
      - bluez
      - bluez-utils
      - blueman
    state: present
  become_user: "{{ ansible_user }}"
  when: devices.bluetooth.install | default(false)

- name: Enable and start Bluetooth service
  ansible.builtin.systemd:
    name: bluetooth
    enabled: true
    state: started
  become: true
  when: devices.bluetooth.install | default(false)

