---
- name: bluetooth
  block:
    - name: install bluetooth packages
      pacman:
        name:
          - bluez
          - bluez-utils
          - blueman

    - name: enable bluetooth
      service:
        name: bluetooth
        enabled: yes
