---
- name: CUPS をインストール
  aur:
    name:
      - cups              # 印刷システム
    state: present
    use: paru
  become: false

- name: Canon LBP ドライバをインストール
  aur:
    name:
      - libxml2-legacy    # cndrvcups-lt の依存 (ABI 互換)
      - libglade          # cndrvcups-lt の依存
      - cndrvcups-lt      # Canon LBP6040 ドライバ
    state: present
    use: paru
  become: false

- name: cups.service を有効化
  ansible.builtin.systemd:
    name: cups
    enabled: true
    state: started
  become: true
