---
- name: install cups
  pacman:
    name:
      - cups
      - gutenprint
      - sane
      - simple-scan

- name: enable cups
  service:
    name: cups
    enabled: yes

- name: install sane
  pacman:
    name:
      - sane
      - simple-scan
