---
- name: Install CUPS
  aur:
    name:
      - cups        # printing system
      - ghostscript # required by cups-filters universal filter
    state: present
    use: paru
  become: false

- name: Install Canon LBP driver
  aur:
    name:
      - libxml2-legacy # dependency for cndrvcups-lt (ABI compatibility)
      - cndrvcups-lt # Canon LBP6040 driver
    state: present
    use: paru
  become: false

- name: Enable cups.service
  ansible.builtin.systemd:
    name: cups
    enabled: true
    state: started
  become: true
