---
- name: change default shell for user
  user:
    name: "{{ maintain_user }}"
    shell: /bin/fish

- name: clone dotfiles
  become: true
  become_user: "{{ maintain_user }}"
  git:
    repo: https://github.com/mikamo3/dotfiles
    dest: "/home/{{ maintain_user }}/.kawazu/dotfiles"
    update: no
    version: "{{ dotfiles.branch }}"
  register: result_clone_dotfiles

- name: apply dotfiles
  become: true
  become_user: "{{ maintain_user }}"
  command: "bash -c 'source /usr/lib/kawazu/kawazu.sh;yes | KAWAZU_ROOT_DIR=/usr/lib/kawazu kawazu -f link'"
  register: result_apply_dotfiles
  ignore_errors: true
  when: result_clone_dotfiles.changed

- name: xdg-user-dirs-update
  become: true
  become_user: "{{ maintain_user }}"
  shell: LC_ALL=C xdg-user-dirs-update --force

- name: Remove user dir (jp)
  become: true
  become_user: "{{ maintain_user }}"
  file:
    path: "/home/{{ maintain_user }}/{{ item }}"
    state: absent
  with_items:
    - ダウンロード
    - テンプレート
    - デスクトップ
    - ドキュメント
    - ビデオ
    - 音楽
    - 画像
    - 公開

- name: create dirs
  become: true
  become_user: "{{ maintain_user }}"
  file:
    path: "/home/{{ maintain_user }}/{{ item }}"
    state: directory
  with_items:
    - Pictures/wallpapers
    - Pictures/screenshot
    - .local/log
    - google-drive

- name: update fish plugin
  become: true
  become_user: "{{ maintain_user }}"
  command: "fish -c 'fisher update'"

- name: enable services
  become: true
  become_user: "{{ maintain_user }}"
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
    scope: user
  with_items:
    - psd.service
    - gcr-ssh-agent.socket
