- block:
    - name: install
      pacman:
        name:
          - vi
          - fzf
          - powerline
          - unrar
          - unzip
          - zip
          - p7zip
          - lha
          - xz
          - bat
          - htop
          - exa
          - ripgrep
          - neofetch
          - unarchiver
          - xsel
          - xclip
          - pkgfile
          - vim
          - neovim
          - usbutils
          - the_silver_searcher
          - jq
          - wget
          - dmidecode
    - name: install (from aur)
      become: true
      become_user: aur
      aur:
        name:
          - procs
  tags:
    - cui
    - utils
