- block:
    - name: install lightdm-webkit-theme-litarvan
      pacman:
        name: lightdm-webkit-theme-litarvan

    - name: configure lightdm-webkit.conf
      lineinfile:
        path: /etc/lightdm/lightdm-webkit2-greeter.conf
        regexp: '^\s*webkit_theme\s*=\s*.*'
        line: "webkit_theme=litarvan"
        insertafter: '\[greeter]'
  tags:
    - gui
    - lightdm
