- block:
    - name: update pacman cache
      pacman:
        update_cache: yes
      changed_when: False

    - name: install reflector
      pacman:
        name: reflector
      register: reflector_output

    - name: run reflector
      command: reflector --country 'JP' --latest 5 --sort rate --save /etc/pacman.d/mirrorlist
      when: reflector_output.changed

    - name: reflector hook
      block:
        - name: create hooks directory
          file:
            path: /etc/pacman.d/hooks
            state: directory
            owner: root
            group: root
            mode: 0755
        - name: copy pacman hooks
          copy:
            src: mirrorupgrade.hook
            dest: /etc/pacman.d/hooks/mirrorupgrade.hook

    - name: add user for exec yay
      block:
        - name: create user aur
          user:
            name: aur
            group: wheel
        - name: edit sudoers file
          lineinfile:
            path: /etc/sudoers
            line: "aur ALL=(ALL) NOPASSWD: /usr/bin/pacman"
            validate: "visudo -cf %s"

    - name: install yay
      become: yes
      become_user: aur
      aur:
        use: makepkg
        name: yay
    - name: install powerpill
      become: yes
      become_user: aur
      aur:
        name: powerpill
      register: powerpill_output
    - name: config pacman.conf for powerpill
      lineinfile:
        path: /etc/pacman.conf
        regexp: "^ .*SigLevel"
        line: "SigLevel = PackageRequired"
    - name: enable powerpill for aur user
      become: yes
      become_user: aur
      command: yay --save --pacman powerpill
      when: powerpill_output.changed
    - name: install base packages
      pacman:
        name:
          - base
          - base-devel
          - archlinux-keyring
          - networkmanager
          - inetutils
          - pacman-contrib

  tags:
    - system
    - package
