---
- name: load group_vars
  debug: var=groups
- name: load host_vars
  debug: var=hostvars
- name: load host_vars
  debug: var=piyo
- name: reg
  shell: cat /etc/arch-release
  register: hoge
- name: out
  debug: var=hoge.stdout_lines[0]
- name: withitems
  debug: var=item
  with_items:
    - "{{ bootloader.entries }}"
