---
# GUI environment orchestrator - selects appropriate components based on inventory

- name: install GUI common components
  include_role:
    name: gui/common
  tags: [gui, gui-common]

- name: install Wayland protocol support
  include_role:
    name: gui/wayland
  when: gui.desktop in ['hyprland', 'sway', 'gnome']
  tags: [gui, gui-wayland]

- name: install Xorg protocol support
  include_role:
    name: gui/xorg
  when: gui.desktop in ['i3']
  tags: [gui, gui-xorg]

- name: install Hyprland desktop environment
  include_role:
    name: gui/hyprland
  when: gui.desktop | default('hyprland') == 'hyprland'
  tags: [gui, gui-hyprland]

- name: install i3 desktop environment
  include_role:
    name: gui/i3
  when: gui.desktop | default('hyprland') == 'i3'
  tags: [gui, gui-i3]

- name: install Sway desktop environment
  include_role:
    name: gui/sway
  when: gui.desktop | default('hyprland') == 'sway'
  tags: [gui, gui-sway]

- name: install GNOME desktop environment
  include_role:
    name: gui/gnome
  when: gui.desktop | default('hyprland') == 'gnome'
  tags: [gui, gui-gnome]

- name: install Ly display manager
  include_role:
    name: gui/ly
  when: gui.display_manager | default('ly') == 'ly'
  tags: [gui, gui-ly]

- name: install LightDM display manager
  include_role:
    name: gui/lightdm
  when: gui.display_manager | default('ly') == 'lightdm'
  tags: [gui, gui-lightdm]

- name: install GDM display manager
  include_role:
    name: gui/gdm
  when: gui.display_manager | default('ly') == 'gdm'
  tags: [gui, gui-gdm]
