- block:
    - name: install
      become: true
      become_user: aur
      aur:
        name:
          - i3-wm
          - i3status
          - dmenu
          - picom
          - dex
          - dunst
          - polybar
          - rofi
    - name: set default session
      lineinfile:
        path: /etc/lightdm/lightdm.conf
        regexp: "^user-session="
        line: "user-session=i3"
        insertafter: '\[Seat:\*\]'

  tags:
    - gui
    - windowmanager
    - i3
