---
# Base graphics packages for all configurations
# Mesa provides OpenGL/Vulkan/EGL implementations needed by Wayland compositors
- name: install base graphics packages
  pacman:
    name:
      - mesa # OpenGL/Vulkan implementation
      - mesa-utils # Graphics debugging tools (glxinfo, vulkaninfo)
  when: graphics.driver != 'none'

# Virtual machine graphics
- name: install virtio graphics driver
  pacman:
    name:
      - xf86-video-qxl
  when: graphics.driver == 'virtio'

# Intel integrated graphics
- name: install Intel graphics driver
  pacman:
    name:
      - intel-media-driver # Modern VA-API driver (replaces libva-intel-driver)
      - vulkan-intel # Vulkan support
  when: graphics.driver == 'intel'

# NVIDIA graphics
- name: install NVIDIA graphics driver
  pacman:
    name:
      - nvidia-dkms
      - nvidia-utils
      - nvidia-settings
  when: graphics.driver == 'nvidia'

# AMD graphics
- name: install AMD graphics driver
  pacman:
    name:
      - vulkan-radeon # Vulkan support
      - libva-mesa-driver # VA-API support
  when: graphics.driver == 'amd'

# Hardware acceleration support
- name: install hardware acceleration packages
  pacman:
    name:
      - libva-utils
      - vdpauinfo
  when:
    - graphics.driver in ['intel', 'amd', 'nvidia']
    - graphics.hw_accel | default(true)
