---
- name: install pipewire core packages
  pacman:
    name:
      - pipewire
      - wireplumber
      - pipewire-pulse
      - pipewire-alsa
      - pipewire-jack

- name: install pipewire GUI tools
  become: true
  become_user: aur
  aur:
    name:
      - helvum
