---
- name: install CUPS printing system
  pacman:
    name:
      - cups
      - gutenprint

- name: enable CUPS service
  service:
    name: cups
    enabled: yes

- name: install scanner support
  pacman:
    name:
      - sane
      - simple-scan
