---
- name: Install Docker
  community.general.pacman:
    name:
      - docker
      - docker-compose
      - docker-buildx
    state: present
  become: true

- name: Configure NVIDIA runtime for Docker
  ansible.builtin.command:
    cmd: nvidia-ctk runtime configure --runtime=docker
    creates: /etc/docker/daemon.json
  become: true
  when:
    - devices.gpu.type == 'nvidia'
    - devices.gpu.cuda | default(false)
  notify: restart docker

- name: Install Docker TUI tools
  aur:
    name:
      - lazydocker  # Docker TUI
      - ctop        # container monitor
    state: present
    use: paru
  become: false

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  become: true

- name: Enable and start docker.service
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
  become: true

- name: Install distrobox
  community.general.pacman:
    name: distrobox
    state: present
  become: true
