- name: install git utils
  become: true
  become_user: aur
  aur:
    name:
      - github-cli
      - gibo
- name: install commitizen
  npm:
    name: commitizen
    global: yes
- name: install cz-emoji
  npm:
    name: cz-emoji
    global: yes
