---
- import_tasks: editor.yml
  when: development.editor

- import_tasks: git_tools.yml
  when: development.git_tools

- import_tasks: cli_tools.yml
  when: development.cli_tools

- import_tasks: docker.yml
  when: development.docker | default(true)
