---
- name: install browsers
  become: true
  become_user: aur
  aur:
    name:
      - chromium
      - firefox
      - firefox-i18n-ja
      - google-chrome

- name: profile-sync-daemon
  block:
    - name: install profile-sync-daemon
      pacman:
        name: profile-sync-daemon

    - name: add sudo for use overlayfs
      lineinfile:
        path: /etc/sudoers.d/20-psd-overlay-helper
        line: "{{ maintain_user }} ALL=(ALL) NOPASSWD: /usr/bin/psd-overlay-helper"
        create: yes
        mode: 0644
        validate: "visudo -cf %s"
