---
- name: set root password
  user:
    name: root
    password: "{{ secret.user.password | password_hash('sha512')}}"
- name: add user
  user:
    name: "{{ secret.user.name }}"
    append: yes
    groups:
      - wheel
    uid: "{{ user.uid }}"
    shell: "{{ user.shell }}"
    password: "{{ secret.user.password | password_hash('sha512')}}"
    generate_ssh_key: yes
    ssh_key_bits: 521
    ssh_key_type: ecdsa
    ssh_key_file: .ssh/id_ecdsa
    ssh_key_passphrase: "{{ secret.user.password | password_hash('sha512')}}"
- name: set sudo config
  template:
    src: sudoers.j2
    dest: /etc/sudoers
    mode: "440"
    owner: root
    group: root
