---
- name: Install 1Password (GUI + CLI)
  aur:
    name:
      - 1password              # GUI (official AUR)
      - 1password-cli          # op command
    state: present
    use: paru
  become: false
