---
- block:
    - name: install
      pacman:
        name:
          - bluez
          - bluez-utils
          - blueman
          - pulseaudio-alsa
          - pulseaudio-bluetooth
    - name: enable bluetooth
      service:
        name: bluetooth
        enabled: yes
  tags:
    - system
    - bluetooth
