---
- block:
    - name: install
      pacman:
        name:
          - bluez
          - bluez-utils
          - blueman
          - pulseaudio-alsa
          - pulseaudio-bluetooth
  tags:
    - system
    - bluetooth
