---
devices:
  gpu:
    type: none          # intel / amd / nvidia / vm / none
    cuda: false         # only used when type is nvidia
  audio: false          # Audio support
  bluetooth: false      # Bluetooth support
  printer: false        # Printer support
