---
- block:
    - name: install
      become: yes
      become_user: aur
      aur:
        name: ananicy-git
    - name: enable
      service:
        name: ananicy.service
        enabled: yes
  tags:
    - system
    - ananicy
