---
- name: install storage tools
  become: true
  become_user: aur
  aur:
    name:
      - rclone
      - inotify-tools
      - veracrypt
- name: enable user_allow_other_mounts
  lineinfile:
    path: /etc/fuse.conf
    regexp: "^#?user_allow_other$"
    line: "user_allow_other"
    state: present
