---
# Storage role main tasks - Storage, backup, and encryption tools

- name: Install cloud storage sync tools
  aur:
    name:
      - rclone                  # Cloud storage sync
    state: present
  become_user: "{{ ansible_user }}"
  when: storage.cloud_sync

- name: Install encryption tools
  aur:
    name:
      - veracrypt               # Disk encryption utility
    state: present
  become_user: "{{ ansible_user }}"
  when: storage.encryption

- name: Install NFS utilities
  aur:
    name:
      - nfs-utils               # NFS client and server utilities
    state: present
  become_user: "{{ ansible_user }}"
  when: storage.nfs

- name: Configure NFS server
  ansible.builtin.include_tasks: nfs_server.yml
  when: storage.nfs and storage.nfs_server is defined and storage.nfs_server.enabled

- name: Configure NFS client
  ansible.builtin.include_tasks: nfs_client.yml
  when: storage.nfs and storage.nfs_client is defined and storage.nfs_client.enabled

- name: Configure FUSE for storage applications
  ansible.builtin.lineinfile:
    path: /etc/fuse.conf
    regexp: '^#user_allow_other'
    line: 'user_allow_other'
    backup: true
  become: true
  when: storage.cloud_sync or storage.encryption