---
- import_tasks: btrfs_mounts.yml
  when: storage.btrfs_mounts is defined

- import_tasks: cloud_sync.yml
  when: storage.cloud_sync

- import_tasks: encryption.yml
  when: storage.encryption

- import_tasks: nfs.yml
  when: storage.nfs

- import_tasks: iscsi.yml
  when: storage.iscsi
