---
# Shell configuration - Fish shell setup (packages only)

- name: Configure Fish shell as default
  block:
    - name: Check if fish is installed
      ansible.builtin.command: which fish
      register: fish_check
      failed_when: false
      changed_when: false

    - name: Add fish to /etc/shells if not present
      ansible.builtin.lineinfile:
        path: /etc/shells
        line: /usr/bin/fish
        create: true
      become: true
      when: fish_check.rc == 0

    - name: Set fish as default shell for user
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        shell: /usr/bin/fish
      become: true
      when: 
        - shell_config.default_shell == "fish"
        - fish_check.rc == 0