- block:
    - name: install
      pacman:
        name:
          - arduino
          - arduino-avr-core

    - name: join lock uucp groups
      user:
        name: "{{ secret.user.name }}"
        append: yes
        groups:
          - lock
          - uucp
  tags:
    - development
    - m5stack
