---
all:
  hosts:
    mainpc:
      ansible_host: 192.168.100.100
      ansible_user: ansible
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    nucbox:
      ansible_host: 192.168.100.20
      ansible_user: mikamo
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    sandbox:
      ansible_host: 192.168.122.222
      ansible_user: mikamo
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    kamo3ai:
      ansible_host: 192.168.100.10
      ansible_user: mikamo
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
