---
all:
  hosts:
    mainpc:
      ansible_host: 192.168.100.100
      ansible_user: ansible
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    nucbox:
      ansible_host: 192.168.10.220
      ansible_user: ansible
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
