- block:
  - name: install
    pacman: 
      name:
        - fcitx
        - fcitx-configtool
        - fcitx-gtk2
        - fcitx-gtk3
        - fcitx-mozc
        - fcitx-qt5

  - name: configure fcitx
    copy:
      src: 60-export-fcitx-config.sh
      dest: /etc/X11/xinit/xinitrc.d/60-export-fcitx-config.sh
      mode: "0755"
  tags:
    - gui
    - fcitx