---
- name: lightdm
  block:
    - name: install lightdm
      pacman:
        name: lightdm

    - name: enable lightdm
      service:
        name: lightdm.service
        enabled: yes

    - name: install lightdm-mini-greeter
      become: true
      become_user: aur
      aur:
        name: lightdm-mini-greeter

    - name: configure lightdm.conf
      lineinfile:
        path: /etc/lightdm/lightdm.conf
        regexp: '^\s*greeter-session=.*'
        line: "greeter-session=lightdm-mini-greeter"
        insertafter: '\[Seat:\*\]'

    - name: configure lightdm-mini-greeter.conf
      lineinfile:
        path: /etc/lightdm/lightdm-mini-greeter.conf
        regexp: '^\s*user\s*=.*'
        line: "user = {{ maintain_user }}"
        insertafter: '\[greeter\]'
  notify: restart lightdm
