---
- name: install gui utils
  become: true
  become_user: aur
  aur:
    name:
      - alacritty
      - nemo
      - catfish
      - leafpad
      - featherpad
      - xdg-user-dirs
      - xorg-xeyes
      - network-manager-applet
      - file-roller
      - filezilla
      - remmina
      - freerdp
      - qbittorrent
      - keepassxc
      - gparted
      - dex
      - archlinux-wallpaper
      - 1password

- name: install seahose
  pacman:
    name:
      - gnome-keyring
      - seahorse
      - libsecret
