- name: install video driver (virtualbox)
  pacman:
    name: xf86-video-vesa,xf86-video-fbdev
  when: driver.display == "virtualbox"

- name: install video driver (amdgpu)
  pacman:
    name: 
    - xf86-video-amdgpu
    - libva-mesa-driver
    - lib32-libva-mesa-driver
  when: driver.display == "amd"

- name: install video driver (catalyst)
  pacman:
    name: xf86-video-amdgpu
  when: driver.display == "catalyst"

- name: install video driver (intel)
  pacman:
    name: xf86-video-intel
  when: driver.display == "intel"

- name: install video driver (nouveau)
  pacman:
    name: xf86-video-nouveau
  when: driver.display == "nouveau"

- name: install video driver (nvidia)
  pacman:
    name: nvidia,nvidia-utils
  when: driver.display == "nvidia"

- name: virtualbox-guest-utils
  block:
    - name: install virtualbox-guest-utils
      pacman:
        name: virtualbox-guest-utils
    - name: enable virtualbox-guest-utils
      service:
        name: vboxservice
        enabled: yes
      notify: restart vboxservice
  when: driver.virtualbox == true

- name: install libva-utils
  pacman:
    name: libva-utils

- name: install pulse audio
  pacman:
    name: pulseaudio,pavucontrol