---
- name: Reload systemd unit definitions
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Create reflector config directory
  ansible.builtin.file:
    path: /etc/xdg/reflector
    state: directory
    mode: "0755"
  become: true

- name: Deploy reflector.conf
  ansible.builtin.template:
    src: reflector.conf.j2
    dest: /etc/xdg/reflector/reflector.conf
    mode: "0644"
  become: true
  notify: run reflector

- name: Enable reflector.timer
  ansible.builtin.systemd:
    name: reflector.timer
    enabled: true
    state: started
  become: true

- name: Enable paccache.timer
  ansible.builtin.systemd:
    name: paccache.timer
    enabled: true
    state: started
  become: true

- name: Enable fwupd-refresh.timer
  ansible.builtin.systemd:
    name: fwupd-refresh.timer
    enabled: true
    state: started
  become: true
  when: base.fwupd | default(true)
