- include: timesyncd.yml
  tags: timesyncd
- include: update.yml
  tags: update
- include: timezone.yml
- include: host.yml
- include: locale.yml
  tags: locale
- include: user.yml
  tags: user
- include: package.yml
  tags: package
- include: driver.yml
  tags: driver
- include: printer.yml
  tags: printer
- include: man.yml
  tags: man
- include: runtime.yml
  tags: runtime 