---
# Base role main tasks

- name: Include package management tasks
  ansible.builtin.import_tasks: packages.yml
  tags: [base, packages]

- name: Include common utilities installation
  ansible.builtin.import_tasks: common_utils.yml
  tags: [base, utils]

- name: Include system basic configuration
  ansible.builtin.import_tasks: system_basic.yml
  tags: [base, system]

- name: Include system services configuration
  ansible.builtin.import_tasks: services.yml
  tags: [base, services]

- name: Include network configuration
  ansible.builtin.import_tasks: network.yml
  tags: [base, network]

- name: Include system configuration
  ansible.builtin.import_tasks: config.yml
  tags: [base, config]

- name: Include security configuration
  ansible.builtin.import_tasks: security.yml
  tags: [base, security]