---
- include: timesyncd.yml
  tags: timesyncd
- include: update.yml
  tags: update
- include: timezone.yml
- include: host.yml
- include: locale.yml
- include: user.yml
- include: package.yml
- include: driver.yml
- include: printer.yml
  tags: printer
- include: man.yml
  tags: man