---
# Network configuration using NetworkManager

- name: Configure static IP address
  block:
    - name: Check if NetworkManager is running
      ansible.builtin.systemd:
        name: NetworkManager
        state: started
      become: true

    - name: Create static network connection profile (autoconnect disabled)
      community.general.nmcli:
        conn_name: "static-{{ static_network.interface }}"
        ifname: "{{ static_network.interface }}"
        type: ethernet
        ip4: "{{ static_network.ip_address }}/{{ static_network.prefix }}"
        gw4: "{{ static_network.gateway }}"
        dns4: "{{ static_network.dns_servers }}"
        method4: manual
        state: present
      become: true
  when: static_network.enabled | default(false)
