---
# Network configuration using NetworkManager

- name: Configure static IP address (connection file only)
  block:
    - name: Create NetworkManager connection directory
      ansible.builtin.file:
        path: /etc/NetworkManager/system-connections
        state: directory
        mode: '0755'
      become: true

    - name: Create static network connection file
      ansible.builtin.copy:
        content: |
          [connection]
          id=static-{{ base.static_network.interface }}
          type=ethernet
          interface-name={{ base.static_network.interface }}
          autoconnect=false
          
          [ethernet]
          
          [ipv4]
          method=manual
          address1={{ base.static_network.ip_address }}/{{ base.static_network.prefix }},{{ base.static_network.gateway }}
          dns={{ base.static_network.dns_servers | join(';') }}
          
          [ipv6]
          method=ignore
          
          [proxy]
        dest: "/etc/NetworkManager/system-connections/static-{{ base.static_network.interface }}.nmconnection"
        mode: '0600'
        backup: true
      become: true
      notify: reload networkmanager
  when: base.static_network.enabled | default(false)
