---
- name: Install base packages
  community.general.pacman:
    name:
      # build/kernel
      - base-devel
      - linux-headers

      # filesystem
      - btrfs-progs
      - dosfstools

      # documentation
      - man-db
      - man-pages

      # package management
      - pacman-contrib
      - reflector

      # network/transfer
      - curl
      - wget
      - rsync

      # firewall (nftables backend + iptables CLI compatibility)
      - iptables-nft

      # misc tools
      - git-crypt
    state: present
  become: true

- name: Install CPU microcode (AMD)
  community.general.pacman:
    name: amd-ucode
    state: present
  become: true
  when: devices.cpu.vendor | default('none') == 'amd'

- name: Install CPU microcode (Intel)
  community.general.pacman:
    name: intel-ucode
    state: present
  become: true
  when: devices.cpu.vendor | default('none') == 'intel'

- name: Install extra kernel headers (for DKMS etc.)
  community.general.pacman:
    name: "{{ base.extra_kernel_headers }}"
    state: present
  become: true
  when: base.extra_kernel_headers | length > 0

- name: Install fwupd
  community.general.pacman:
    name: fwupd
    state: present
  become: true
  when: base.fwupd | default(true)
