---
- name: install base packages
  become: true
  become_user: aur
  aur:
    name:
      - archlinux-keyring
      - base
      - base-devel
      - bash-completion
      - bat
      - btop
      - coreutils
      - dmidecode
      - exa
      - firejail
      - fish
      - fisher
      - fzf
      - ghq
      - git
      - htop
      - inetutils
      - iperf
      - jdk-openjdk
      - jq
      - less
      - lha
      - linux-headers
      - linux-zen-headers
      - man-db
      - handlr
      - neofetch
      - neovim
      - net-tools
      - networkmanager
      - nodejs
      - npm
      - ntfs-3g
      - p7zip
      - pacman-contrib
      - pkgfile
      - procs
      - python
      - python-pip
      - ripgrep
      - smartmontools
      - sshpass
      - starship
      - tcpdump
      - the_silver_searcher
      - tmux
      - tmux-plugin-manager
      - unarchiver
      - unrar
      - unzip
      - usbutils
      - vi
      - wget
      - xz
      - yarn
      - zip
