---
# Package management configuration

- name: Update pacman configuration
  ansible.builtin.template:
    src: pacman.conf.j2
    dest: /etc/pacman.conf
    backup: true
    mode: '0644'
  become: true
  notify: update package database

- name: Update package database
  community.general.pacman:
    update_cache: true
  become: true

- name: Install essential packages
  community.general.pacman:
    name: "{{ base_packages }}"
    state: present
  become: true
  register: essential_packages_result

- name: Install AUR helper (yay) with makepkg
  aur:
    name: yay
    use: makepkg
  become_user: "{{ ansible_user }}"

- name: Run reflector to optimize mirrorlist
  ansible.builtin.command: reflector --country 'JP' --latest 5 --sort rate --save /etc/pacman.d/mirrorlist
  become: true
  when: essential_packages_result.changed and 'reflector' in base_packages

- name: Setup reflector hook for automatic mirror updates
  block:
    - name: Create pacman hooks directory
      ansible.builtin.file:
        path: /etc/pacman.d/hooks
        state: directory
        owner: root
        group: root
        mode: '0755'
      become: true

    - name: Install mirrorupgrade hook
      ansible.builtin.copy:
        src: mirrorupgrade.hook
        dest: /etc/pacman.d/hooks/mirrorupgrade.hook
        owner: root
        group: root
        mode: '0644'
      become: true

- name: Install AUR packages
  aur:
    name: "{{ aur_packages }}"
    state: present
  become_user: "{{ ansible_user }}"
  when: aur_packages is defined and aur_packages | length > 0