---
# Package management configuration

- name: Update pacman configuration
  ansible.builtin.template:
    src: pacman.conf.j2
    dest: /etc/pacman.conf
    backup: true
    mode: '0644'
  become: true
  notify: update package database

- name: Update package database
  community.general.pacman:
    update_cache: true
  become: true

- name: Install AUR helper (yay) first
  block:
    - name: Check if yay is installed
      ansible.builtin.command: which yay
      register: yay_check
      failed_when: false
      changed_when: false

    - name: Install yay from AUR (if not present)
      when: yay_check.rc != 0
      block:
        - name: Clone yay repository
          ansible.builtin.git:
            repo: https://aur.archlinux.org/yay.git
            dest: /tmp/yay
            force: true
          become_user: "{{ ansible_user }}"

        - name: Build and install yay
          ansible.builtin.shell: |
            cd /tmp/yay
            makepkg -si --noconfirm
          become_user: "{{ ansible_user }}"
          
        - name: Clean up yay build directory
          ansible.builtin.file:
            path: /tmp/yay
            state: absent

- name: Install essential packages
  community.general.pacman:
    name: "{{ base_packages }}"
    state: present
  become: true

- name: Install AUR packages
  aur:
    name: "{{ aur_packages }}"
    state: present
  become_user: "{{ ansible_user }}"
  when: aur_packages is defined and aur_packages | length > 0