---
- name: pacman.conf を配置
  ansible.builtin.template:
    src: pacman.conf.j2
    dest: /etc/pacman.conf
    backup: true
    mode: "0644"
  become: true

- name: pacman キャッシュ更新
  community.general.pacman:
    update_cache: true
  become: true
