---
- name: install docker
  pacman:
    name: docker,docker-compose

- name: enable docker
  service:
    name: docker.service
    enabled: yes

- name: add {{ maintain_user }} to group docker
  user:
    name: "{{ maintain_user }}"
    groups: docker
    append: yes

- name: install cronie
  pacman:
    name: cronie

- name: enable cronie
  service:
    name: cronie
    enabled: true

- name: enable sshd
  service:
    name: sshd
    enabled: true
