---
# System services configuration

- name: Enable and start NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager
    enabled: true
    state: started
  become: true

- name: Enable and start SSH daemon
  ansible.builtin.systemd:
    name: sshd
    enabled: true
    state: started
  become: true

- name: Enable and start systemd-timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    enabled: true
    state: started
  become: true

- name: Verify service status
  ansible.builtin.command: systemctl is-active {{ item }}
  register: service_status
  changed_when: false
  failed_when: false
  loop:
    - NetworkManager
    - sshd
    - systemd-timesyncd

- name: Display service status
  ansible.builtin.debug:
    msg: "{{ item.item }} is {{ item.stdout }}"
  loop: "{{ service_status.results }}"