---
- name: "install {{ microcode }}-ucode"
  pacman:
    name: "{{ microcode }}-ucode"
  when: microcode is defined

- name: change mkinitcpio.conf
  lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: '^HOOKS=\(\s*base\s+(?!.*\bmicrocode\b).*\)$'
    line: HOOKS=(base microcode \g<1>)
    backrefs: yes
    state: present

- name: copy hostname
  template:
    src: hostname.j2
    dest: /etc/hostname
    mode: 0644

- name: copy hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    mode: 0644

- name: enable suspend
  lineinfile:
    path: /etc/systemd/logind.conf
    regexp: '^\s*HandlePowerKey='
    line: "HandlePowerKey=suspend"
    insertafter: '\[login\]'
