---
- name: systemd-logind 電源ボタン挙動を設定
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    regexp: "^#?HandlePowerKey="
    line: "HandlePowerKey=suspend"
    backup: true
  become: true
  notify: restart systemd-logind

- name: systemd sleep 設定
  ansible.builtin.lineinfile:
    path: /etc/systemd/sleep.conf
    regexp: "^#?{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
    backup: true
  become: true
  loop:
    - { key: "AllowSuspend", value: "yes" }
    - { key: "AllowHibernation", value: "no" }
    - { key: "AllowSuspendThenHibernate", value: "no" }
    - { key: "AllowHybridSleep", value: "no" }
  notify: restart systemd-logind

- name: journald 設定
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "^#?{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
    backup: true
  become: true
  loop: "{{ base.journald | dict2items }}"
  notify: restart journald

- name: systemd-oomd を有効化
  ansible.builtin.systemd:
    name: systemd-oomd
    enabled: true
    state: started
  become: true
