- name: configure timesyncd
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    mode: "0644"

- name: enable timesyncd
  service:
    name: systemd-timesyncd
    enabled: yes
    state: started