- name: enable suspend
  lineinfile:
    path: /etc/systemd/logind.conf
    regexp: '^\s*HandlePowerKey='
    line: "HandlePowerKey=suspend"
    insertafter: '\[login\]'
  tags:
    - system 
    - suspend 

