- block:
    - name: install virtualbox-guest-utils
      pacman:
        name: virtualbox-guest-utils
    - name: enable vboxservice
      service:
        name: vboxservice
        enabled: yes
  when: ansible_facts['virtualization_type'] == 'virtualbox'
  tags:
    - system
    - driver
