# btrfsパーティショニング・サブボリューム作成
# inventoriesで指定したディスクに対して実行

- name: Create GPT partition table
  community.general.parted:
    device: "{{ target_disk }}"
    label: gpt
  become: true

- name: Create EFI system partition
  community.general.parted:
    device: "{{ target_disk }}"
    number: 1
    part_type: primary
    part_start: 1MiB
    part_end: 1GiB
    flags:
      - esp
    state: present
  become: true

- name: Create root partition
  community.general.parted:
    device: "{{ target_disk }}"
    number: 2
    part_type: primary
    part_start: 1GiB
    part_end: 100%
    state: present
  become: true

- name: Format EFI partition with FAT32
  ansible.builtin.command: "mkfs.fat -F 32 {{ target_disk }}1"
  become: true

- name: Create btrfs filesystem on root partition
  community.general.filesystem:
    fstype: btrfs
    dev: "{{ target_disk }}2"
    force: yes
  become: true

# btrfsサブボリューム作成
- name: Create btrfs subvolumes
  community.general.btrfs_subvolume:
    name: "/{{ item }}"
    filesystem_device: "{{ target_disk }}2"
    state: present
  loop:
    - "@"
    - "@home"
    - "@.snapshots"
    - "@pkg"
    - "@log"
  become: true
