---
# Arch Linux 初期セットアップ用 role: init
# 必要に応じて tasks を追加してください

- name: Include btrfs partitioning tasks
  ansible.builtin.import_tasks: btrfs_partition.yml

- name: Include time sync tasks
  ansible.builtin.import_tasks: time_sync.yml

- name: Set timezone to Asia/Tokyo
  ansible.builtin.command: timedatectl set-timezone Asia/Tokyo
  become: true

- name: Include chroot system setup tasks
  ansible.builtin.include_tasks: chroot_setup.yml

- name: Generate fstab with genfstab
  ansible.builtin.shell: genfstab -U /mnt > /mnt/etc/fstab
  become: true

- name: Include ansible setup tasks
  ansible.builtin.include_tasks: ansible_setup.yml
