---
- name: Install CAD applications
  aur:
    name:
      - freecad                 # 3D parametric CAD
      - librecad                # 2D CAD (DXF support)
      - kicad                   # electronics / PCB design
      - kicad-library           # KiCad symbol / footprint libraries
      - kicad-library-3d        # KiCad 3D model libraries
    state: present
    use: paru
  become: false
  when: cad.install
